### ISSUE TITLE
2 1/2 Major issues

### ISSUE THREAD

**Issue by geraldmwangi** [moddevices/mod-duo-issues#13]
Hi Guys ,
I've been testing the mod some more, and tried to build up some bigger pedalboards (7fx+Guitarix AmpSim) and I have some rants/issues I've run into:
1) When toggleing the on/off switches of the various fx to off, the cpu load does'nt go down. This suggests to me that the process Callback of each fx is still called when the fx is 'off'. Am I wrong? In this case shouldn't the inputs of each fx just be memcpy'd to the outputs?

2) This one is a bigger deal breaker: The webserver becomes unresponsive when the mod is running a high workload like my big pedalboard (cpu > 90%). This cannot be: At least when building a tcp connection to the webserver the fxs should be bypassed in the sense of issue 1), since the UI takes absolute precedence. When the mod site is loaded the fxs can be turned on again. Of course not all UI actions should take precedence over the audio. But the loading of the mod website and the deleting of an fx must take precedence (all fxs toggled to off when these actions are initiated and turned on thereafter!).

3) This is only a minor issue/idea. How about rating the plugins by their cpu usage: in the pluginselection below the pedalboard each plugin could have an indicator showing how much cpu would be left after loading the plugin: say the current workload is cpu=45%, and a partikular fx requires 10% cpu. Then the indicator next to the plugin in the plugin selection should read 45%-10%=35% cpu left. This way people can directly see how much space they have.

I have encountered some bugs with my big pedalboard, but they may be related to the issues I've already reported. I'll dig into them on the weekend.

**Comment by falkTX** [comment]
I wish this had been in separate issues... (how and when are we closing this one?)
anyway, let's see...

1) this is expected. we do not stop processing plugins when bypassed, but instead we feed it a clean/zeroed buffer.
I was not part of the MOD team when this decision was made, but afaik it's done mostly for not breaking delay and other time-based effects.

I don't see this changing anytime soon.
What I hope happens is that LV2 gets an official 'bypass' spec. This has been already discussed on the LV2 mailing list, but (I believe) no final consensus was reached.
A few plugins already implement an internal bypass mode (artyfx, rakarrack, calf), so when the LV2 bypass spec is decided we just need to start using it.

2) Because we still have some pending driver fixes, we will not do this right now.
It's very hard to fine-tune the processes when we don't truly know how the driver will behave.
We'll look into this at a later date.

3) somewhat same answer as point 2.
in my view we could have a 'performance rating' system (1-5 stars) instead of raw percentage values.
a few plugins will consume more or less cpu depending on the data you feed them, so this is not a simple matter..
for example, some synths have an almost-static cpu load with or without midi events while others only consume cpu when playing notes.

PS: next time please report issues separately, and preferably only in one place. Thanks!

**Comment by geraldmwangi** [comment]
Hi falktx,
This double posting was ment to show how serious I think issue 2) is! But nevertheless you are right, I won't double post again and I'll split the future issues up. Your response to issue 3) makes sense, so consider that closed. I just think issue 1+2 have the potential to mess up market reception of the mod!

**Comment by thijz** [comment]
2016-03-04 12:03 GMT+01:00 geraldmwangi notifications@github.com:

> Hi falktx,
> This double posting was ment to show how serious I think issue 2) is! But
> nevertheless you are right, I won't double post again and I'll split the
> future issues up. Your response to issue 3) makes sense, so consider that
> closed. I just think issue 1+2 have the potential to mess up market
> reception of the mod!
> 
> +1
> maybe all plugins should be benchmarked so the real total CPU usage can be
> predicted and the device remains stable
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/moddevices/mod-duo-issues/issues/13#issuecomment-192234854
> .

## 

follow me on my Audio & Linux blog http://audio-and-linux.blogspot.com/ !

**Comment by odurc** [comment]
@geraldmwangi many update has been passed since this post. The current version 0.15.0 has a quite more stable software. Can you please re-test point 2, if possible using same pedalboard as before, and give us a new feedback?

**Comment by geraldmwangi** [comment]
Hi sorry for the late reply. The point 2 seems to be resolved. Thanks

**Comment by odurc** [comment]
I'm closing this issue although issues 1 and 3 still pending. If want to have any further discussion about them I'd ask you to open topics in the forum, one per issue. Thanks.
