### ISSUE TITLE
Sooperlooper play/pause, rec, undo, redo actuators have no 'midi learn'

### ISSUE THREAD

**Issue by geraldmwangi** [moddevices/mod-duo-issues#21]
I'll spare myself exact reproduce steps ;)

**Comment by geraldmwangi** [comment]
I neeeeed this feature!!

**Comment by falkTX** [comment]
this is because there's no "trigger" events in midi-cc.
(also it's something I forgot to test for...)

I'll enable it, but the way to click on the button again might make some midi devices act weird.

to explain, 'trigger' controls automatically reset to their default value after 1 process cycle.
for the GUI and hw controller we have ways to notify the user about this.
but there's no such thing in midi-cc.

**Comment by geraldmwangi** [comment]
you could ofcourse just have the controls just be triggered by positive slope (cc<64 ->cc >64) events and ignore the negative slopes (cc>64->cc<64)

**Comment by geraldmwangi** [comment]
and emit a negative slope to the serial midi out after 1 process cycle

**Comment by falkTX** [comment]
we don't have midi feedback yet.

**Comment by geraldmwangi** [comment]
But once you have midi feedback, the notifications could be realised the way I described it?

**Comment by geraldmwangi** [comment]
Hi, the big file midi_footsw.ttl is at http://pastebin.com/bT2tvnPM

**Comment by falkTX** [comment]
fixed on 0.11.3 release.
