### ISSUE TITLE
TAP Pitch Shifter contains Spectral category duplicated

### ISSUE THREAD

**Issue by SrMouraSilva** [moddevices/mod-duo-issues#28]
In http://api.moddevices.com/lv2/plugins/56c4bdf3770cb318f9cd56c5

TAP Pitch Shifter contains Spectral category duplicated

``` json
{ "author":
   { "email": "devel@moddevices.com",
     "homepage": "http://moddevices.com",
     "name": "MOD Team" },
  "binary": "tap_pitch.so",
  "brand": "TAP",
  "bundle_href": "http://api.moddevices.com/lv2/bundles/56c4bdf3770cb318f9cd56c0/",
  ...
  "category": [ "Spectral", "Spectral", "Pitch Shifter" ],
  ...
}
```

**Comment by falkTX** [comment]
Nice catch!
This is now fixed, we'll deploy the fix to the cloud very soon.
Plugins will have to be rebuilt.

**Comment by SrMouraSilva** [comment]
The others do not have this problem!

Good day

**Comment by falkTX** [comment]
yes, tap-pitch was special because its categories contain 'Spectral' and 'Pitch Shifter'.
on lv2 the 'Pitch Shifter' implies 'Spectral', so the plugin was in a way declaring 'Spectral' twice.

fixed in https://github.com/moddevices/lilvlib/commit/668c2af7476c1fda88feea91656f93383e4bdcd8 by making category items unique.
