### ISSUE TITLE
Performance issues on GxJCM800pre

### ISSUE THREAD

**Issue by jonobacon** [moddevices/mod-duo-issues#30]
When selecting the GxJCM800pre amp (which is a pretty awesome simulator), the audio is incredible choppy - it seems the CPU is maxed out. This issue probably refers to an issue that is documented elsewhere.

**Comment by falkTX** [comment]
This is a sorta known issue.
The guitarix JCM\* plugins are very, very cpu intensive - even for powerful desktop systems.

One of the guitarix developers has a MOD Duo, so hopefully he will be able to optimize it.

**Comment by jonobacon** [comment]
@falkTX thanks for the reply.

Two thoughts:
1. I strikes me that the JCM plugin would be a hugely attractive one to ship on the Mod Duo - there are few plugins that faithfully recreate a known amp sound, so do you think the plugin could be optimized to work on the Mod Duo hardware?
2. For the duration that this plugin doesn't work well, it might be worth hiding it from the store. I know there are Stable/Unstable plugins, but if it doesn't work at all, I don't think it is worth being in the store.

**Comment by falkTX** [comment]
The thing about the store is that the "unstable" plugins should not be visible at all right now.
Our plan is to have separate 'main' and 'user' repositories. The non-stable plugins will go into the 'users' repo. Developers will be able to upload plugins to 'users' repo.
Because of time constrains we only added the 'stable' button and don't have this repository separation yet.

Wherever the JCM plugin will be working correctly later on is up to the upstream developers, but I'm hopeful they'll make it. :)

**Comment by jonobacon** [comment]
@falkTX got it.

I guess this opens up another question: has the mod team identified a core set of "priority" plugins that you want to ensure work perfectly? I suspect like any kind of pluggable software environment, around 10% of the plugins will be used 80% of the time - do you have a sense of which plugins are most important?

I ask because I suspect that upsteam may either (a) not prioritize getting this working on Mod Duo or (b) not be interested, and I think this amp could be a jewel in the crown on the Mod Duo.

**Comment by falkTX** [comment]
The plugins that we ensure that work perfectly are the ones on the 'stable' channel.
Every single plugin that goes into stable must really be stable.

Regarding JCM, we know the developer and met him several times.
He has shown definitive interest on MOD Duo (that's why he has one right now ;)). We'll let him know that this plugin is important. :)
Thanks.

**Comment by jonobacon** [comment]
Thanks, @falkTX - happy to help with testing if I can. :-)

**Comment by thijz** [comment]
Op 18-apr.-2016 18:45 schreef "Jono Bacon" notifications@github.com:

> @falkTX got it.
> 
> I guess this opens up another question: has the mod team identified a
> core set of "priority" plugins that you want to ensure work perfectly? I
> suspect like any kind of pluggable software environment, around 10% of the
> plugins will be used 80% of the time - do you have a sense of which plugins
> are most important?

Good point. I think that same 20/80 principle should also be applied to the
MOD gui :
I consider myself a 'tech savvy' person, but i still was overwhelmed by the
number of pedals and the complexity of some of those pedals
How about making a 'staff pick' of the 'best' (meaning the 'most common'
10% fx) reverb, distortion, delay... pedals available in a 'staff pick'
category.  this could be a new category next to the existing delay,
distortion ... categories
The user can then use these fx as a starting point to 'smoothly' migrate
from their current pedals to the mod.

**Comment by harryhaaren** [comment]
@thijz : re "Staff Picks" a +1 from me. I've seen some amazing sounds from MOD, but have the same "swimming in plugins" feeling sometimes.

**Comment by falkTX** [comment]
GxJCM800pre is live on the store now! :D

Still takes quite some CPU, but now it's actually usable.
