### ISSUE TITLE
knob 2 long press to select banks not working after changes in banks

### ISSUE THREAD

**Issue by ghost** [moddevices/mod-duo-issues#39]
Hello there!

When I make changes to the banks on the browser, long pressing the knob 2 does not go to the bank menu.

I have to restart the MODDuo to get it back to work.

(it's my first time using git-hub, how do I had labels?)

**Comment by odurc** [comment]
Hello @ruiestamine :)

That's because the access to banks, via controller, is blocked when you're using web browser interface. If you close the browser tab you'll have this function back to controller. 
I'm going to create a pop info in the controller with such information.

(only staff is able to apply labels ;)

**Comment by falkTX** [comment]
A new MOD version is out which shows some information on the controller display when it's not possible to navigate through banks.
Hopefully it clears up any confusion.
