### ISSUE TITLE
Audio cables suddenly turn turquois in 1.2.0.236-RC1

### ISSUE THREAD

**Issue by MrBollie** [moddevices/mod-duo-issues#81]
## Description

I tried dragging a jack from one icon to the other and it suddenly changed color.

## How to reproduce

It happens quite randomly.
 
## Expected/suggested solution

Replace this text with how you would expect this to work.

## Additional information
* release: v1.2.0
* controller: 4bac7f9

Also provide some information about your system if possible.

* Operating system: Linux
* System version: ARCH
* Firefox 49.0.2

![screenshot from 2016-11-11 23-21-56](https://cloud.githubusercontent.com/assets/20420706/20232777/eedaa1e4-a86a-11e6-8856-ee4c0512741d.png)

**Comment by falkTX** [comment]
You found the way to connect ports using touch devices :)
Because on those devices click&drag is not easy to do, you can single click on a port to select it, then click on the target port to connect it.

So yeah, this is intentional.
If you don't want to see those types of cables hold the mouse down when doing connections.
